bookapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name = 'home'),
    path('all_books', views.all_books, name = 'all_books'),
    path('genre/<str:slug>', views.category_detail, name = 'category_detail'),
    path('pdf/<str:slug>', views.book_detail, name = 'book_detail'),
    path('searched_books', views.search_book, name = 'book_search'),
    path('register', views.register_page, name = 'register'),
    path('login', views.login_page, name = 'login'),
    path('logout', views.logout_user, name = 'logout')
]

booksite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('book/', include('bookapp.urls'))
    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField('Categories', max_length=50)
    slug = models.SlugField(max_length = 50)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField(max_length=100)
    cover_image = models.ImageField(upload_to = 'img', blank = True, null = True)
    author = models.CharField(max_length=50)
    summary = models.TextField()
    category = models.ManyToManyField(Category, related_name='books')
    pdf = models.FileField(upload_to='pdf')
    stock = models.PositiveIntegerField(default=0, )
    recommended_books = models.BooleanField(default=False)
    fiction_books = models.BooleanField(default=False)
    business_books = models.BooleanField(default=False)
    

    def __str__(self):
        return self.title

class BookSearch(models.Model):
    name_of_book = models.CharField(max_length=100)
    def __str__(self):
        return self.name_of_book
    
import uuid  # Required for unique book instances
from datetime import date

from django.contrib.auth.models import User  # Required to assign User as a borrower


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)

bookapp/forms.py
from django import forms
from .models import BookSearch
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime

class BookSearchForm(forms.ModelForm):
    name_of_book = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': "form-control me-2", 'placeholder': 'Enter name of book'
    }))
    class Meta:
        model = BookSearch
        fields = ['name_of_book',]

class CreateUserForm(UserCreationForm):
    username = forms.CharField(max_length = 100, widget = forms.TextInput(attrs={
        'class' : 'form-control', 'placeholder': 'Enter Username'
    }))

    email = forms.CharField(max_length = 100, widget = forms.EmailInput(attrs={
        'class' : 'form-control', 'placeholder': 'Enter Email Address'
    }))

    password1 = forms.CharField(max_length = 100, widget = forms.PasswordInput(attrs={
        'class' : 'form-control', 'placeholder': 'At least eight characters'
    }))
    password2 = forms.CharField(max_length = 100, widget = forms.PasswordInput(attrs={
        'class' : 'form-control', 'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class RenewBookForm(forms.Form):
    
    renewal_date = forms.DateField(
            help_text="Enter a date between now and 4 weeks (default 3).")
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

bookapp/views.py
from django.shortcuts import render, redirect
from .models import Book, Category, BookInstance
from django.contrib.auth.forms import UserCreationForm
from  .forms import CreateUserForm, RenewBookForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import login_required, permission_required

def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available copies of books
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_books': num_books, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available, 
                 'num_visits': num_visits},
    )
# Create your views here.
def home(request):
    recommended_books = Book.objects.filter(recommended_books = True)
    fiction_books = Book.objects.filter(fiction_books = True)
    business_books = Book.objects.filter(business_books = True)

    return render(request, 'home.html', {'recommended_books': recommended_books,
    'business_books': business_books, 'fiction_books': fiction_books
    })

    




def all_books(request):
    books = Book.objects.all()
    return render(request, 'all_books.html', {'books':books})

def category_detail(request, slug):
    category = Category.objects.get(slug = slug)
    return render(request, 'genre_detail.html', {'category': category})



@login_required(login_url='login')
def book_detail(request, slug):
    book = Book.objects.get(slug = slug)
    book_category = book.category.first()
    similar_books = Book.objects.filter(category__name__startswith = book_category)
    return render(request, 'book_detail.html', {'book': book, 'similar_books': similar_books})




def search_book(request):
    searched_books = Book.objects.filter(title__icontains = request.POST.get('name_of_book', default="")) 
            
    return render(request, 'search_book.html', {'searched_books':searched_books})







class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission."""
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

    
@login_required 
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


def register_page(request):
    register_form = CreateUserForm()
    if request.method == 'POST':
        register_form = CreateUserForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            messages.info(request, "Account Created Successfully!")
            return redirect('login')
           
    return render(request, 'register.html', {'register_form': register_form})

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password1')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, "Invalid Credentials")
        
    
    return render(request, 'login.html', {})

def logout_user(request):
    logout(request)
    return redirect('home')

bookapp/templates/all_books.html
{% extends 'base.html' %}
     {% block title %}
     <title>Book Site | All Books</title>
     {% endblock %}
 
   
     {% block content %}
 <div class = 'container'style = "padding-left: 0px">
     <div class = 'row'>
        {% for book in books %}
         <div class = 'col- col-sm-4 col-md-4 col-lg-3 col-xl-2'>
             <a href = "{% url 'book_detail' book.slug %}">
                 
     <div>
         <div class="uk-card uk-card-default uk-card-body"> 
             <img src = "{{book.cover_image.url}}">
             
             
         </div>
     </div>
           
         </a>
     </div>
     {% endfor %}
    
 </div>
 {% endblock %}

bookapp/templates/book_detail.html
{% extends 'base.html' %}

{% block title %}
     <title>Book Site | Book Detail </title>
     {% endblock %}

{% block content %}

<div class = 'container' style = 'border: 2px solid black; width: 80%'>
    <div class = 'row' style = 'border: 2px solid black'>
        <div class = 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4'>
            
            <div id = 'imageContainer'>
                <img src = '{{book.cover_image.url}}'>
            </div>
        </div>
        <div class = 'col-12 col-sm-12 col-md-6 col-lg-8 col-xl-8'>
            <div id = 'summaryContent'>
                <h1>{{book.title}}</h1>
                <h2>by: <strong>{{book.author}}</strong></h2>
                <h3>Book Summary:</h3>
                <h4>{{book.summary}}</h4>
                {% if book.stock <= 0 %}
    <h5>Out of stock</h5>
    {% endif %}
                
                
                
                <a href = '{{book.pdf.url}}' download="{{book.pdf.url}}">
                <button id = 'download'>
                    Download PDF
                    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                      </svg>
                </button>
            </a>
        </div>
        <div style="margin-left:20px;margin-top:20px">
            <h4>Copies</h4>
            
            {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
            <p><strong>Imprint:</strong> {{copy.imprint}}</p>
            <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
            
            {% endfor %}
            </div>
        </div>
    </div>
</div>


<div class = 'container'>
    <div class = 'row'>
        <h4>Similar Books</h4>            
    </div>
    <div class = 'row'>
        {% for similar_book in similar_books %}
        <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
      <a href = "{% url 'book_detail' similar_book.slug %}">
        <div>
          <div class="uk-card uk-card-default uk-card-body"> 
              <img src = "{{similar_book.cover_image.url}}">
             
          </div>
      </div>
    </a>
    </div>
    {% endfor %}

    </div>
    
</div>
{% endblock %}

bookapp/templates/book_renew_librarian.html
{% extends "base.html" %}

{% block content %}
    <h1>Renew: {{book_instance.book.title}}</h1>
    <p>Borrower: {{book_instance.borrower}}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{book_instance.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

bookapp/templates/bookinstance_list_borrowed_all.html
{% extends "base.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book_detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

bookapp/templates/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book_detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

bookapp/templates/genre_detail.html
{% extends 'base.html' %}

{% block title %}
     <title>Book Site | Genre Books </title>
     {% endblock %}
{% block content %}
<div class = 'container'>
    <div class = 'row'><h4></h4></div>
    <div class = 'row'>
      {% for book in category.books.all %}
      <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
        <a href = "{% url 'book_detail' book.slug %}">
          <div>
            <div class="uk-card uk-card-default uk-card-body"> 
                <img src = "{{book.cover_image.url}}">
               
            </div>
        </div>
      </a>
      </div>
      {% endfor %}
      
      
    </div>
  </div>
  {% endblock %}

bookapp/templates/home.html
{% extends 'base.html' %}

{% block title %}
    <title>Book Site | Home</title>
    {% endblock %}
  {% block content %}  
<div class = 'container'>
  <div class = 'row'><h4>Recommended Books</h4></div>
  <div class = 'row'>
    {% for book in recommended_books %}
    <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
      <a href = "{% url 'book_detail' book.slug %}">
        <div>
          <div class="uk-card uk-card-default uk-card-body"> 
              <img src = "{{book.cover_image.url}}">
             
          </div>
      </div>
    </a>
    </div>
    {% endfor %}
  </div>
</div>


<div class = 'container'>
  <div class = 'row'><h4>Top Fiction Books</h4></div>
  <div class = 'row'>
    {% for book in fiction_books %}
    <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
      <a href = "">
        <div>
          <div class="uk-card uk-card-default uk-card-body"> 
             <img src = "{{book.cover_image.url}}">
          </div>
      </div>
    </a>
    </div>
    {% endfor %}
  </div>
</div>


<div class = 'container'>
    <div class = 'row'><h4>Top Business Books</h4></div>
    <div class = 'row'>
        {% for book in business_books %}
      <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
        <a href = "">
          <div>
            <div class="uk-card uk-card-default uk-card-body"> 
               <img src = "{{book.cover_image.url}}">
            </div>
        </div>
      </a>
      </div>
      {% endfor %}
    </div>
  </div>
  

{% endblock %}

bookapp/templates/login.html
{% extends 'base.html' %}

{% block title %}
<title>Book Site | Login</title>
{% endblock %}


{% block content %}


<div id = 'container' style = 'height: 400px'>
    <div class = 'header'>
      <h2>Login</h2>
    </div>
    <form action = '#' method = 'POST'>
      {% csrf_token %}
      <div id = 'form-control'>
        <label>Username:</label>
        <input type="text" name="username" class="form-control" placeholder="Enter Username" maxlength="100" autofocus="" required="" id="id_username">
      </div>
  
     
  
      <div id = 'form-control'>
        <label>Passowrd</label>
        <input type="password" name="password1" class="form-control" placeholder="At least eight characters" maxlength="100" required="" id="id_password1">
      </div>
      {% for message in messages %}
      <p class  = 'successMsg'>{{message}}</p>
      {% endfor%}
      <div id = 'haveAnAccount'>
        <p>Don't have an account?</p>
        <a href = "{% url 'register' %}"><strong>Register</strong></a>
      </div>
      
      <button type = 'submit' id = 'submitButton'>Login</button>
    </form>
    
  </div>
  
   {% endblock %}

bookapp/templates/register.html
{% extends 'base.html' %}

{% block title %}
<title>Book Site | Register</title>
{% endblock %}


{% block content %}
<div id = 'container'>
    <div class = 'header'>
      <h2>Create an account</h2>
    </div>
    <form action = '#' method = 'POST'>
      {% csrf_token %}
      <div id = 'form-control'>
          <label>Username:</label>
          <!-- <input type="text" name="username" class="form-control" placeholder="Enter Username" maxlength="100" autofocus="" required=""> -->
          {{register_form.username}}
        </div>
        <div id = 'form-control'>
          <label>Email:</label>
          <!-- <input type= "email" name="email" class="form-control" placeholder="Enter EmailAddress" maxlength="100" autofocus="" required=""> -->
          {{register_form.email}}
        </div>
  
      <div id = 'form-control'>
          <label>Password:</label>
          <!-- <input type="password" name="password1" class="form-control" placeholder="At least eight characters" maxlength="100" autofocus="" required=""> -->
          {{register_form.password1}}
        </div>
  
       <div id = 'form-control'>
          <label>Confirm Password:</label>
          <!-- <input type="password" name="password2" class="form-control" placeholder="Confirm password" maxlength="100" autofocus="" required=""> -->
          {{register_form.password2}}
        </div>
      
        {{register_form.errors}}

  
      <div id = 'haveAnAccount'>
        <p>Already have an account?</p>
        <a href = "{% url 'login' %}"><strong>Login</strong></a>
      </div>
      <button type = 'submit' id = 'submitButton'>Register</button>
    </form>
  </div>
  {% endblock %}

bookapp/templates/search_book.html
{% extends 'base.html' %}
{% block title %}
<title>Book Site | Searched Books</title>
{% endblock %}

{% block content %}
<div class = 'container'>
    <div class = 'row'><h4>Searched Book</h4></div>
    <div class = 'row'>
        {% if searched_books %}
       {% for book in searched_books %}
      <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
        <a href = "">
          <div>
            <div class="uk-card uk-card-default uk-card-body"> 
                <img src = "{{book.cover_image.url}}">
               
            </div>
        </div>
      </a>
      </div>
      {% endfor %}
      {% else %}
      <div class = 'row'>
          <h3>Book Not Available! Check Back Later</h3>
      </div>
      {% endif %}
      

    </div>
  </div>
  {% endblock %}